# Generated by Django 5.2.15 on 2026-06-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=100)),
                ('null_count', models.PositiveIntegerField(default=0)),
                ('unique_count', models.PositiveIntegerField(default=0)),
                ('classification', models.CharField(blank=True, max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='datasets.dataset')),
            ],
            options={
                'ordering': ['column_name'],
                'unique_together': {('dataset', 'column_name')},
            },
        ),
    ]
