# Generated by Django 5.2.15 on 2026-06-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveDataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sensitive_columns', models.PositiveIntegerField(default=0)),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_report', to='datasets.dataset')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('sensitivity_type', models.CharField(max_length=100)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('sample_value', models.CharField(blank=True, max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_fields', to='governance.sensitivedatareport')),
            ],
            options={
                'ordering': ['-match_count', 'column_name'],
            },
        ),
    ]
